import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// COMPONENTS
import Header from "./component/header";
import Footer from "./component/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden bg-white`}
      >
        {/* MAIN WRAPPER */}
        <div className="flex flex-col min-h-screen w-full overflow-x-hidden">

          {/* HEADER */}
          <header className="w-full overflow-x-hidden">
            <Header />
          </header>

          {/* PAGE CONTENT */}
          <main className="flex-1 w-full overflow-x-hidden">
            {children}
          </main>

          {/* FOOTER */}
          <footer className="w-full overflow-x-hidden">
            <Footer />
          </footer>

        </div>
      </body>
    </html>
  );
}